create table public.assessments (
  id uuid not null default gen_random_uuid (),
  original_filename text null,
  pdf_path text null,
  options jsonb null,
  result jsonb null,
  google_form jsonb null,
  created_at timestamp with time zone null default now(),
  user_id text null,
  constraint assessments_pkey primary key (id),
  constraint assessments_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_assessments_user_id on public.assessments using btree (user_id) TABLESPACE pg_default;



create table public.batches (
  id bigint generated by default as identity not null,
  name text null,
  user_id text null,
  constraint batches_pkey primary key (id),
  constraint batches_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_batches_user_id on public.batches using btree (user_id) TABLESPACE pg_default;




create table public.lesson_plans (
  id uuid not null default gen_random_uuid (),
  original_filename text null,
  pdf_path text null,
  options jsonb null,
  result jsonb not null,
  created_at timestamp with time zone not null default now(),
  user_id text null,
  constraint lesson_plans_pkey primary key (id),
  constraint lesson_plans_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_lesson_plans_created_at on public.lesson_plans using btree (created_at desc) TABLESPACE pg_default;

create index IF not exists idx_lesson_plans_user_id on public.lesson_plans using btree (user_id) TABLESPACE pg_default;





create table public.students (
  student_id bigint generated by default as identity not null,
  name text null,
  email text null,
  batch_id bigint null,
  user_id text null,
  constraint students_pkey primary key (student_id),
  constraint students_batch_id_key unique (student_id),
  constraint students_batch_id_fkey foreign KEY (batch_id) references batches (id),
  constraint students_user_id_fkey foreign KEY (user_id) references users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_students_user_id on public.students using btree (user_id) TABLESPACE pg_default;




create table public.users (
  id text not null,
  email text not null,
  full_name text null,
  avatar_url text null,
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  credits integer null default 10,
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email)
) TABLESPACE pg_default;

create index IF not exists idx_users_email on public.users using btree (email) TABLESPACE pg_default;

create trigger update_users_updated_at BEFORE
update on users for EACH row
execute FUNCTION update_updated_at_column ();